name: BERT-NAML.VER${llm_ver}.D${model.config.hidden_size}.L${model.config.news_config.layer_split}.Lora${model.config.news_config.lora}
config:
  use_news_content: true
  use_fast_eval: ${fast_eval}$
  max_news_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  news_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
    weights_dir: data/${data.name}/bert-${llm_ver}-split
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
