name: PLMNR-DCN.D64
config:
  use_news_content: true
  hidden_size: 64
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  dnn_dropout: 0.1
  dnn_batch_norm: false
  cross_num: 3
  news_config:
    num_attention_heads: 8
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    flatten: false
    max_pooling: false
