#name: bert-token
#embeddings:
#  -
#    vocab_name: english
#    vocab_type: bert_tf
#    path: PLM/bert-base-uncased
#    frozen: true

name: english-token
embeddings:
  -
    vocab_name: english
    vocab_type: numpy
    path: data/bert-token.12L.npy
    frozen: ${frozen}$